contents:
  - name: Hash
    codes:
      - hash.hpp
  - name: KMP
    codes:
      - kmp.hpp
  - name: Z Function
    codes:
      - z_function.hpp
  - name: Suffix Array
    codes:
      - suffix_array.hpp
  - name: Suffix Automaton
    codes:
      - suffix_automaton.hpp
  - name: Aho-Corasick
    codes:
      - aho_corasick.hpp
  - name: Palindrome Automaton
    codes:
      - palindrome_automaton.hpp
  - name: Lyndon
    codes:
      - lyndon.hpp
