contents:
  - name: Configuration
    codes:
      - config.hpp
  - name: Point
    codes:
      - point.hpp
  - name: Line
    codes:
      - line.hpp
  - name: Polygon
    codes:
      - polygon.hpp
  - name: Convex
    codes:
      - convex.hpp
  - name: Half-Plane
    codes:
      - halfplane.hpp
  - name: Circle
    codes:
      - circle.hpp
