contents:
  - name: Core
    directory: core
  - name: Algorithm
    directory: algorithm
  - name: Data Structure
    directory: data_structure
  - name: Graph
    directory: graph
  - name: Math
    directory: math
  - name: String
    directory: string
  - name: Tree
    directory: tree
  - name: Geometry
    directory: geometry
  - name: Config
    directory: config
  - name: Online
    directory: online
  - name: Onsite
    directory: onsite
