contents:
  - name: ModInt
    codes:
      - modint.hpp
  - name: Number Theory
    codes:
      - number_theory.hpp
  - name: Prime
    codes:
      - prime.hpp
  - name: Combinatorics
    codes:
      - comb.hpp
  - name: Linear Algebra
    codes:
      - linear_algebra.hpp
  - name: Matrix Tree
    codes:
      - matrix_tree.hpp
  - name: Floor Sum
    codes:
      - floor_sum.hpp
  - name: Fast Walsh-Hadamard Transform
    codes:
      - fast_walsh_hadamard.hpp
  - name: Polynomial
    directory: polynomial
