contents:
  - name: NTT
    codes:
      - ntt.hpp
  - name: Inverse
    codes:
      - inverse.hpp
  - name: Log and Exp
    codes:
      - log_exp.hpp
  - name: Square Root
    codes:
      - sqrt.hpp
  - name: Multipoint
    codes:
      - multipoint.hpp
