contents:
  - name: HashMap
    codes:
      - hashmap.hpp
  - name: Cartesian Tree
    codes:
      - cartesian.hpp
  - name: Chtholly Tree
    codes:
      - chtholly.hpp
  - name: Binary Alarm
    codes:
      - binary_alarm.hpp
  - name: Link-Cut Tree
    codes:
      - link_cut_tree.hpp
