contents:
  - name: Fenwick
    codes:
      - fenwick.hpp
  - name: Sparse Table
    codes:
      - sparse_table.hpp
  - name: DSU
    codes:
      - dsu.hpp
  - name: Weighted DSU
    codes:
      - weighted_dsu.hpp
  - name: Rollback DSU
    codes:
      - rollback_dsu.hpp
  - name: Binary Trie
    codes:
      - binary_trie.hpp
  - name: Link-Cut Tree
    codes:
      - link_cut_tree.hpp
