contents:
  - name: SCC
    codes:
      - scc.hpp
  - name: EBCC
    codes:
      - ebcc.hpp
  - name: Two-SAT
    codes:
      - two_sat.hpp
  - name: Shortest Path
    codes:
      - shortest_path.hpp
  - name: Dinic
    codes:
      - dinic.hpp
  - name: Min-Cost Flow
    codes:
      - min_cost_flow.hpp
  - name: Bipartite Matching
    codes:
      - bipartite_matching.hpp
