contents:
  - name: LCA
    codes:
      - lca.hpp
  - name: HLD
    codes:
      - hld.hpp
  - name: Tree Difference
    codes:
      - tree_difference.hpp
  - name: DSU on Tree
    codes:
      - dsu_on_tree.hpp
  - name: Centroid Decomposition
    codes:
      - centroid_decomposition.hpp
